### ISSUE TITLE
Does not work with prompt containing emoji.

### ISSUE THREAD

**Issue by makeprompt** [rassi0429/novelai-metadata-viewer#1]
Hello, thanks for this useful site !
It did not work well with prompt containing emoji.
Sample prompt:"👍,London"
Sample image data 
![👍,London s-751530908](https://user-images.githubusercontent.com/116355282/198042081-b0deb3f4-9f3b-4724-841c-0027dfb6626b.png)

Display in Google Chrome developer tools
> content.js:1 Uncaught TypeError: t.drop is not a function
>     at content.js:1:38311
>     at Object.handleEvent (content.js:1:41813)
> (anonymous) @ content.js:1
> handleEvent @ content.js:1
> vue@2:11 TypeError: Cannot read properties of undefined (reading 'split')
>     at Or.onFileChange ((index):186:52)

Sorry for my bad English.
This text was translated by DeepL.

**Comment by rassi0429** [comment]
報告ありがとうございます！　マルチバイト文字のパースを実装していなかったので、この問題が起きていたようです。
正常にパースできるようになりました。
バージョン1.0.1として反映させていただきました。ありがとうございました。

Thanks for the report!　It seems that this problem was happening because we had not implemented parsing of multibyte characters.
It can now be parsed correctly.
I have reflected it as version 1.0.1. Thank you very much.

![image](https://user-images.githubusercontent.com/91118218/198175507-b054b05f-ce03-4172-8ff4-a74f771f5bf4.png)
